# Generated by Django 4.0 on 2022-03-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_personne', models.CharField(max_length=30, verbose_name='Nom_personne')),
                ('adresse_personne', models.CharField(max_length=150, verbose_name='Adresse_personne')),
                ('telephone_personne', models.IntegerField(verbose_name='Telephone de la personne')),
                ('numero_identification', models.IntegerField(verbose_name='Numero_identification')),
                ('date_operation', models.DateField(verbose_name='Date de l operation')),
                ('lieu_operation', models.CharField(max_length=150, verbose_name='Lieu_operation')),
                ('type_operation', models.CharField(max_length=150, verbose_name='type_operation')),
                ('nom_agence', models.CharField(max_length=150, verbose_name='nom_agence')),
                ('adresse_agence', models.CharField(max_length=150, verbose_name='adresse_agence')),
                ('contact_agence', models.IntegerField(verbose_name='contact_agence')),
                ('numero_compte', models.IntegerField(verbose_name='numero_compte')),
                ('type_compte', models.CharField(max_length=150, verbose_name='type_compte')),
            ],
        ),
    ]
